### ISSUE TITLE
long pattern guards

### ISSUE THREAD

**Issue by sp0** [sp0/rustfmt#12]
Current formatting of long pattern gaurds are bad:
```
match foo {
    (&Token::ModSep, &Token::OpenDelim(DelimToken::Brace)) if line.typ ==
        LineType::Use => false,
}
```
How should this be formatted?

**Comment by madmalik** [comment]
I think 
```
match foo {
    (&Token::ModSep, &Token::OpenDelim(DelimToken::Brace)) 
        if line.typ == LineType::Use => false,
}
```
could be the best option. Wrapping the if statement in invisible braces may do the trick?

**Comment by sp0** [comment]
I suppose that is the most logical. The problem I find with formatting like this is when the arm is a block, you get formatting like this:
```
match foo {
    (&Token::ModSep, &Token::OpenDelim(DelimToken::Brace)) 
        if line.typ == LineType::Use => {
        let a = 2;
        let b = 2;
    }
}
```
At I glance, it is not immediatly obvious where the condition ends and the block starts. I have also seen code avoiding the issue by simply moving the brace in this case:
```
match foo {
    (&Token::ModSep, &Token::OpenDelim(DelimToken::Brace)) 
        if line.typ == LineType::Use => 
    {
        let a = 2;
        let b = 2;
    }
}
```
Or you could indent the block further:
```
match foo {
    (&Token::ModSep, &Token::OpenDelim(DelimToken::Brace)) 
        if line.typ == LineType::Use => {
            let a = 2;
            let b = 2;
        }
}
```
It would also be an option to change the indent width or continuation indent width so they are different.  I think having an indent width of 2 spaces, and a continuation indent of 4 spaces would fix this issue, which imo makes sense. I actually prefer an indent width of 2 spaces in rust, since it it oftens tends to be rightward drifting language. However, the current standard is an indent width of 4 spaces. Maybe an indent width of 4 spaces and a continuation width of 8 spaces could work.
