### ISSUE TITLE
Continuation line breaking between patterns

### ISSUE THREAD

**Issue by sp0** [sp0/rustfmt#23]
Current output:
```
match self.current().tok {
    Token::Eq | Token::Le | Token::EqEq | Token::Ne | Token::Ge | Token::Gt |
        Token::AndAnd | Token::OrOr | Token::BinOp(..) | Token::BinOpEq(..) => {
        TokenType::BinaryOperator
    }
}
```
The break after '|' is not usually indented, like so:
```
match self.current().tok {
    Token::Eq | Token::Le | Token::EqEq | Token::Ne | Token::Ge | Token::Gt |
    Token::AndAnd | Token::OrOr | Token::BinOp(..) | Token::BinOpEq(..) => {
        TokenType::BinaryOperator
    }
}
```

**Comment by sp0** [comment]
We will also probably want a style option to break after every |, if we need to break any '|'. This could probably be included in the default style as well.

**Comment by madmalik** [comment]
In the style guide following style is recommended: http://aturon.github.io/style/whitespace.html#matches
But it says it's deprecated, without mentioning an alternative...

Beside that, breaking _before_ the "|" looks nice and creates more visual distinction between the individual matcharms.

**Comment by sp0** [comment]
Sure, that works as well. I poked around the rustc source, it seems to break before and after "|" inconsistently. Not that we should look to rustc should be taken for good formatting style :). I changed it to break before. I suppose we could easily add a style option for either.

I'm closing this issue, the main problem was fixed.
