### ISSUE TITLE
Macro definitions using braces ruins following output

### ISSUE THREAD

**Issue by sp0** [sp0/rustfmt#5]
If a file has a defintion of a macro using the brace variant, the following code until the end of the file is formatted incorrectly.

Example output:

```
macro_rules!assert_fmt_eq {
    ($s: expr) => (assert_eq!(fmt($s), $s))
}

    fn foo() {
    let a = 12;
}
```

**Comment by madmalik** [comment]
I've fixed the spacing issue after the "!". Together with the other changes in the unwrapped line parser this issue should be solved. 

I've added your example as a test.
